import type { Property, Project } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { url: "https://picsum.photos/seed/default/600/400", hint: "default image"};
    return { url: img.imageUrl, hint: img.imageHint };
}

export const properties: Property[] = [
  {
    id: '1',
    ownerId: 'user1',
    status: 'active',
    mode: 'sale',
    type: 'villa',
    title: 'Luxury Waterfront Villa',
    description: 'A stunning luxury waterfront villa overlooking the Arabian Sea, perfect for a family seeking upscale living in Kovalam. Features premium interiors, a private pool, and a large scenic terrace.',
    price: 35000000,
    areaSqft: 4500,
    bedrooms: 5,
    bathrooms: 6,
    furnishing: 'furnished',
    parking: '3_car_garage',
    floor: 0,
    ageYears: 2,
    facing: 'South-West',
    amenities: ['Swimming Pool', 'Gym', 'Security', 'Private Garden', 'Sea View'],
    location: {
      lat: 8.4004,
      lng: 76.9787,
      geohash: '9xj4b',
      locality: 'Kovalam',
      city: 'Trivandrum',
      state: 'Kerala',
    },
    media: {
      coverUrl: getImage('villa_1').url,
      imageHint: getImage('villa_1').hint,
      urls: [getImage('villa_1').url, getImage('interior_1').url, getImage('pool_1').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    ownerId: 'user2',
    status: 'active',
    mode: 'rent',
    type: 'apartment',
    title: 'Premium Sky Penthouse',
    description: 'Experience modern city living at its finest in this premium sky penthouse in Marine Drive, Kochi. Floor-to-ceiling windows offer panoramic views of the backwaters. Fully furnished.',
    rentMonthly: 75000,
    areaSqft: 2200,
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'furnished',
    parking: '2_car_underground',
    floor: 45,
    ageYears: 5,
    facing: 'North',
    amenities: ['Concierge', 'Rooftop Deck', 'Fitness Center', 'Lake View'],
    location: {
      lat: 9.9816,
      lng: 76.2730,
      geohash: '9xjef',
      locality: 'Marine Drive',
      city: 'Kochi',
      state: 'Kerala',
    },
    media: {
      coverUrl: getImage('apartment_1').url,
      imageHint: getImage('apartment_1').hint,
      urls: [getImage('apartment_1').url, getImage('interior_2').url, getImage('view_1').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    ownerId: 'user3',
    status: 'active',
    mode: 'sale',
    type: 'apartment',
    title: 'Elegant Heritage Apartment',
    description: 'A beautifully designed apartment in the heart of historic Fort Kochi, blending vintage colonial aesthetics with luxury modern fittings. Includes a charming balcony.',
    price: 12500000,
    areaSqft: 1500,
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'semi-furnished',
    parking: 'street_parking',
    floor: 4,
    ageYears: 50,
    facing: 'East',
    amenities: ['Balcony', 'Elevator', 'Hardwood Floors'],
    location: {
      lat: 9.9658,
      lng: 76.2421,
      geohash: '9xjee',
      locality: 'Fort Kochi',
      city: 'Kochi',
      state: 'Kerala',
    },
    media: {
      coverUrl: getImage('apartment_2').url,
      imageHint: getImage('apartment_2').hint,
      urls: [getImage('apartment_2').url, getImage('interior_3').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    ownerId: 'user4',
    status: 'active',
    mode: 'sale',
    type: 'plot',
    title: 'Spacious Residential Plot',
    description: 'An expansive residential plot in a peaceful suburb of Palakkad. Perfect for building your dream home with plenty of space for organic farming and landscaping.',
    price: 4500000,
    areaSqft: 10000,
    bedrooms: 0,
    bathrooms: 0,
    furnishing: 'unfurnished',
    parking: 'n/a',
    floor: 0,
    ageYears: 0,
    facing: 'South',
    amenities: [],
    location: {
      lat: 10.7867,
      lng: 76.6548,
      geohash: '9xjgc',
      locality: 'Kakkayur',
      city: 'Palakkad',
      state: 'Kerala',
    },
    media: {
      coverUrl: getImage('plot_1').url,
      imageHint: getImage('plot_1').hint,
      urls: [getImage('plot_1').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    ownerId: 'user5',
    status: 'active',
    mode: 'rent',
    type: 'commercial',
    title: 'Elite Commercial Office Space',
    description: 'State-of-the-art office space located near Kochi InfoPark. Ideal for tech startups and IT companies with flexible working floor layouts and high-speed fiber internet.',
    rentMonthly: 120000,
    areaSqft: 3000,
    bedrooms: 0,
    bathrooms: 4,
    furnishing: 'unfurnished',
    parking: 'valet',
    floor: 12,
    ageYears: 3,
    facing: 'West',
    amenities: ['Reception', 'Conference Rooms', '24/7 Access'],
    location: {
      lat: 10.0104,
      lng: 76.3638,
      geohash: '9xjem',
      locality: 'Kakkanad InfoPark',
      city: 'Kochi',
      state: 'Kerala',
    },
    media: {
      coverUrl: getImage('commercial_1').url,
      imageHint: getImage('commercial_1').hint,
      urls: [getImage('commercial_1').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    ownerId: 'user1',
    status: 'active',
    mode: 'sale',
    type: 'villa',
    title: 'Tranquil Plantation Estate',
    description: 'A magnificent tea plantation estate in Munnar, complete with a private cottage, scenic view terraces, and guest quarters. A masterpiece of classic mountain living.',
    price: 55000000,
    areaSqft: 12000,
    bedrooms: 8,
    bathrooms: 10,
    furnishing: 'furnished',
    parking: '5_car_garage',
    floor: 0,
    ageYears: 15,
    facing: 'South',
    amenities: ['Vineyard', 'Horse Stables', 'Guest House', 'Swimming Pool'],
    location: {
      lat: 10.0889,
      lng: 77.0595,
      geohash: '9xjsw',
      locality: 'Munnar',
      city: 'Idukki',
      state: 'Kerala',
    },
    media: {
      coverUrl: getImage('villa_2').url,
      imageHint: getImage('villa_2').hint,
      urls: [getImage('villa_2').url, getImage('interior_4').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    ownerId: 'user2',
    status: 'active',
    mode: 'rent',
    type: 'apartment',
    title: 'Modern Executive Studio',
    description: 'A bright and space-efficient studio apartment near Trivandrum Technopark, tailored for single corporate professionals and tech employees.',
    rentMonthly: 18000,
    areaSqft: 500,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'furnished',
    parking: 'no',
    floor: 3,
    ageYears: 8,
    facing: 'North-East',
    amenities: ['Community Laundry', 'Bike Storage'],
    location: {
      lat: 8.5686,
      lng: 76.8730,
      geohash: '9xj4e',
      locality: 'Kazhakkoottam',
      city: 'Trivandrum',
      state: 'Kerala',
    },
    media: {
      coverUrl: getImage('apartment_3').url,
      imageHint: getImage('apartment_3').hint,
      urls: [getImage('apartment_3').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const projects: Project[] = [
  {
    id: 'proj1',
    name: 'The Sapphire Residences',
    builder: 'Celestial Developers',
    locality: 'Jawahar Nagar',
    city: 'Trivandrum',
    expectedHandoverDate: '2025-12-01',
    priceRangeMin: 15000000,
    priceRangeMax: 45000000,
    amenities: ['Private Beach', 'Infinity Pool', 'Luxury Spa', 'Yacht Club Access'],
    media: {
      coverUrl: getImage('project_1').url,
      imageHint: getImage('project_1').hint,
      urls: [getImage('project_1').url],
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'proj2',
    name: 'Veridian Towers',
    builder: 'Evergreen Holdings',
    locality: 'Vyttila',
    city: 'Kochi',
    expectedHandoverDate: '2026-06-30',
    priceRangeMin: 8500000,
    priceRangeMax: 25000000,
    amenities: ['Sky Garden', 'Smart Home System', 'Olympic-size Pool', 'Co-working Space'],
    media: {
      coverUrl: getImage('project_2').url,
      imageHint: getImage('project_2').hint,
      urls: [getImage('project_2').url],
    },
    createdAt: new Date().toISOString(),
  },
];
