import type { Property, Project } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { url: "https://picsum.photos/seed/default/600/400", hint: "default image"};
    return { url: img.imageUrl, hint: img.imageHint };
}

export const properties: Property[] = [
  {
    id: '1',
    ownerId: 'user1',
    status: 'active',
    mode: 'sale',
    type: 'villa',
    title: 'Modern Villa with Ocean View',
    description: 'A stunning modern villa with breathtaking ocean views, perfect for a family looking for luxury and comfort. Features a private pool and a large terrace.',
    price: 2500000,
    areaSqft: 4500,
    bedrooms: 5,
    bathrooms: 6,
    furnishing: 'furnished',
    parking: '3_car_garage',
    floor: 0,
    ageYears: 2,
    facing: 'South-West',
    amenities: ['Swimming Pool', 'Gym', 'Security', 'Private Garden', 'Ocean View'],
    location: {
      lat: 34.0522,
      lng: -118.2437,
      geohash: '9q5cs',
      locality: 'Beverly Hills',
      city: 'Los Angeles',
      state: 'CA',
    },
    media: {
      coverUrl: getImage('villa_1').url,
      imageHint: getImage('villa_1').hint,
      urls: [getImage('villa_1').url, getImage('interior_1').url, getImage('pool_1').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    ownerId: 'user2',
    status: 'active',
    mode: 'rent',
    type: 'apartment',
    title: 'Luxury Downtown Penthouse',
    description: 'Experience city living at its finest in this luxurious downtown penthouse. Floor-to-ceiling windows offer panoramic city views. Fully furnished with designer pieces.',
    rentMonthly: 12000,
    areaSqft: 2200,
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'furnished',
    parking: '2_car_underground',
    floor: 45,
    ageYears: 5,
    facing: 'North',
    amenities: ['Concierge', 'Rooftop Deck', 'Fitness Center', 'City View'],
    location: {
      lat: 40.7128,
      lng: -74.0060,
      geohash: 'dr5reg',
      locality: 'Financial District',
      city: 'New York',
      state: 'NY',
    },
    media: {
      coverUrl: getImage('apartment_1').url,
      imageHint: getImage('apartment_1').hint,
      urls: [getImage('apartment_1').url, getImage('interior_2').url, getImage('view_1').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    ownerId: 'user3',
    status: 'active',
    mode: 'sale',
    type: 'apartment',
    title: 'Chic Parisian Flat',
    description: 'A beautifully renovated flat in the heart of Paris, featuring classic Haussmannian architecture with modern touches. Includes a charming balcony overlooking the street.',
    price: 1800000,
    areaSqft: 1500,
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'semi-furnished',
    parking: 'street_parking',
    floor: 4,
    ageYears: 50,
    facing: 'East',
    amenities: ['Balcony', 'Elevator', 'Hardwood Floors'],
    location: {
      lat: 48.8566,
      lng: 2.3522,
      geohash: 'u09wj',
      locality: 'Le Marais',
      city: 'Paris',
      state: 'Île-de-France',
    },
    media: {
      coverUrl: getImage('apartment_2').url,
      imageHint: getImage('apartment_2').hint,
      urls: [getImage('apartment_2').url, getImage('interior_3').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    ownerId: 'user4',
    status: 'active',
    mode: 'sale',
    type: 'plot',
    title: 'Spacious Residential Plot',
    description: 'An expansive residential plot in a rapidly developing suburban area. Perfect for building your dream home with plenty of space for a garden and amenities.',
    price: 500000,
    areaSqft: 10000,
    bedrooms: 0,
    bathrooms: 0,
    furnishing: 'unfurnished',
    parking: 'n/a',
    floor: 0,
    ageYears: 0,
    facing: 'South',
    amenities: [],
    location: {
      lat: 28.6139,
      lng: 77.2090,
      geohash: 'tthbp',
      locality: 'Greater Noida',
      city: 'Delhi',
      state: 'DL',
    },
    media: {
      coverUrl: getImage('plot_1').url,
      imageHint: getImage('plot_1').hint,
      urls: [getImage('plot_1').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    ownerId: 'user5',
    status: 'active',
    mode: 'rent',
    type: 'commercial',
    title: 'Prime Office Space in Business Hub',
    description: 'Modern office space located in a bustling business district. Ideal for startups and established companies alike, with flexible floor plans and high-speed internet.',
    rentMonthly: 8000,
    areaSqft: 3000,
    bedrooms: 0,
    bathrooms: 4,
    furnishing: 'unfurnished',
    parking: 'valet',
    floor: 12,
    ageYears: 3,
    facing: 'West',
    amenities: ['Reception', 'Conference Rooms', '24/7 Access'],
    location: {
      lat: 51.5074,
      lng: -0.1278,
      geohash: 'gcpvj',
      locality: 'Canary Wharf',
      city: 'London',
      state: 'ENG',
    },
    media: {
      coverUrl: getImage('commercial_1').url,
      imageHint: getImage('commercial_1').hint,
      urls: [getImage('commercial_1').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    ownerId: 'user1',
    status: 'active',
    mode: 'sale',
    type: 'villa',
    title: 'Countryside Estate with Vineyard',
    description: 'A magnificent countryside estate spanning 10 acres, complete with a private vineyard, horse stables, and a guest house. The main residence is a masterpiece of classic architecture.',
    price: 7800000,
    areaSqft: 12000,
    bedrooms: 8,
    bathrooms: 10,
    furnishing: 'furnished',
    parking: '5_car_garage',
    floor: 0,
    ageYears: 15,
    facing: 'South',
    amenities: ['Vineyard', 'Horse Stables', 'Guest House', 'Swimming Pool'],
    location: {
      lat: 43.7696,
      lng: 11.2558,
      geohash: 'srwut',
      locality: 'Tuscany',
      city: 'Florence',
      state: 'FI',
    },
    media: {
      coverUrl: getImage('villa_2').url,
      imageHint: getImage('villa_2').hint,
      urls: [getImage('villa_2').url, getImage('interior_4').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
    {
    id: '7',
    ownerId: 'user2',
    status: 'active',
    mode: 'rent',
    type: 'apartment',
    title: 'Cozy Studio in Creative District',
    description: 'A bright and cozy studio apartment in a vibrant, artistic neighborhood. Perfect for a single professional or student. Features a modern kitchenette and a space-saving layout.',
    rentMonthly: 2500,
    areaSqft: 500,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'furnished',
    parking: 'no',
    floor: 3,
    ageYears: 8,
    facing: 'North-East',
    amenities: ['Community Laundry', 'Bike Storage'],
    location: {
      lat: 37.7749,
      lng: -122.4194,
      geohash: '9q8yy',
      locality: 'SoMa',
      city: 'San Francisco',
      state: 'CA',
    },
    media: {
      coverUrl: getImage('apartment_3').url,
      imageHint: getImage('apartment_3').hint,
      urls: [getImage('apartment_3').url],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const projects: Project[] = [
  {
    id: 'proj1',
    name: 'The Sapphire Residences',
    builder: 'Celestial Developers',
    locality: 'Palm Jumeirah',
    city: 'Dubai',
    expectedHandoverDate: '2025-12-01',
    priceRangeMin: 3000000,
    priceRangeMax: 10000000,
    amenities: ['Private Beach', 'Infinity Pool', 'Luxury Spa', 'Yacht Club Access'],
    media: {
      coverUrl: getImage('project_1').url,
      imageHint: getImage('project_1').hint,
      urls: [getImage('project_1').url],
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'proj2',
    name: 'Veridian Towers',
    builder: 'Evergreen Holdings',
    locality: 'Midtown',
    city: 'Singapore',
    expectedHandoverDate: '2026-06-30',
    priceRangeMin: 1500000,
    priceRangeMax: 5000000,
    amenities: ['Sky Garden', 'Smart Home System', 'Olympic-size Pool', 'Co-working Space'],
    media: {
      coverUrl: getImage('project_2').url,
      imageHint: getImage('project_2').hint,
      urls: [getImage('project_2').url],
    },
    createdAt: new Date().toISOString(),
  },
];
